app_setup/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from app_setup.views import WelcomeView, CompleteView, EnvironmentView, MigrateView, UserView, FixtureView


urlpatterns = [
    url(r'^$', WelcomeView.as_view(template_name="setup_welcome.html"), name="welcome"),
    url(r'^environment/$', EnvironmentView.as_view(), name="environment"),
    url(r'^migrate/$', MigrateView.as_view(), name="migration"),
    url(r'^user/$', UserView.as_view(), name="user"),
    url(r'^fixture/$', FixtureView.as_view(), name="fixture"),
    url(r'^completed/$', CompleteView.as_view(template_name="setup_completed.html"), name="completed"),
]

neosetup/urls.py
from django.conf.urls import url, include
from app_main.views import MainView

urlpatterns = [
    url(r'^$', MainView.as_view()),
    url(r'^setup/', include("app_setup.urls", namespace="setup")),
]

app_setup/forms.py
# -*- coding: utf-8 -*-
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions


class EnvironmentForm(forms.Form):
    ENGINES = [('sqlite', 'SQLite'),
               ('mysql', 'MySQL'),
               ('postgres', 'PostgreSQL')]

    proxy_name = forms.CharField(label='Proxy Name', max_length=100)
    central_host = forms.CharField(label='Host', max_length=100)
    central_port = forms.IntegerField(label='Port')

    engine = forms.ChoiceField(choices=ENGINES, widget=forms.RadioSelect())
    python = forms.CharField(label='Python Interpreter', max_length=100, required=False, disabled=True)
    host = forms.CharField(label='Host', max_length=100, required=False)
    port = forms.IntegerField(label='Port', required=False)
    name = forms.CharField(label='Database Name', max_length=100, required=False)
    username = forms.CharField(label='Username', max_length=100, required=False)
    password = forms.CharField(label='Password', max_length=100, widget=forms.PasswordInput(), required=False)

    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-sm-2 col-sm-offset-2'
    helper.field_class = 'col-sm-4'
    helper.form_id = 'main-form'
    helper.layout = Layout(
        Fieldset(
            'NEO Server Central',
            'central_host',
            'central_port',
            'proxy_name',
        ),
        Fieldset(
            'Interpreter',
            'python',
        ),
        Fieldset(
            'Database Engine',
            'engine',
        ),
        Fieldset(
            'Database Information',
            'host',
            'port',
            'name',
            'username',
            'password',
            css_class='db'
        ),
        FormActions(
            Submit('save_changes', 'Configure environment.', css_class="btn-primary"),
            css_class='actions'
        )
    )


class UserForm(forms.Form):
    email = forms.EmailField(label='Email', max_length=100)
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', max_length=100, widget=forms.PasswordInput())

    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-2'
    helper.field_class = 'col-lg-4'
    helper.form_id = 'main-form'
    helper.layout = Layout(
        Fieldset(
            'Superuser Information',
            'email',
            'username',
            'password',
        ),
        FormActions(
            Submit('save_changes', 'Create superuser', css_class="btn-primary"),
        )
    )

    # def clean_username(self):
    #     raise forms.ValidationError("Username already exists!")

    # def clean_password(self):
    #     raise forms.ValidationError("El password es muy debil, ponete las eveready.")

app_setup/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib import messages

import os
import sys
import environ
import subprocess
import _mysql

from .forms import EnvironmentForm, UserForm


class WelcomeView(TemplateView):

    def get_context_data(self, **kwargs):
        context = super(WelcomeView, self).get_context_data(**kwargs)
        context['step'] = 1
        return context


class EnvironmentView(View):
    step = 2
    template_name = 'setup_environment.html'
    form_class = EnvironmentForm
    env_separator = '# -- dynamic settings --'

    def clean (self, env_file):
        with open(env_file,"r") as f:
            lines = f.readlines()
        print lines

        with open(env_file,"w") as f:
            ins = True
            for line in lines:
                ins = ins and line.rstrip() != self.env_separator.rstrip()
                if ins:
                    f.write(line)

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial={
            'python': sys.executable,
            'engine': 'sqlite'
        })
        return render(request, self.template_name, {'step': self.step, 'form': form})

    def post(self, request, *args, **kwargs):

        form = self.form_class(request.POST)
        if not form.is_valid():
            return render(request, self.template_name, {'step': self.step, 'form': form})

        env_file = str(settings.ROOT_DIR.path('.env'))
        self.clean(env_file)
        open(env_file, 'a').write('\n')
        open(env_file, 'a').write(self.env_separator)
        open(env_file, 'a').write('\nSETUP_COMPLETED=True')
        open(env_file, 'a').write('\nNEO_CENTRAL_HOST=%s' % form.cleaned_data['central_host'])
        open(env_file, 'a').write('\nNEO_CENTRAL_PORT=%s' % form.cleaned_data['central_port'])
        open(env_file, 'a').write('\nNEO_PROXY_ALIAS=%s' % form.cleaned_data['proxy_name'])

        if form.cleaned_data['engine'] == 'sqlite':
            if not os.path.isfile(str(settings.ROOT_DIR.path(form.cleaned_data['name']))):
                self.clean(env_file)
                messages.error(request, 'Sqlite database file not found. %s' % str(settings.ROOT_DIR.path(form.cleaned_data['name'])))
                return render(request, self.template_name, {'step': self.step, 'form': form})

            open(env_file, 'a').write('\nDATABASE_URL=sqlite:///%s' % str(settings.ROOT_DIR.path(form.cleaned_data['name'])))
        else:
            if form.cleaned_data['engine'] == 'mysql':
                try:
                    db = _mysql.connect(
                            form.cleaned_data['host'], 
                            form.cleaned_data['username'], 
                            form.cleaned_data['password'], 
                            form.cleaned_data['name'])
                except _mysql.Error as e:
                    messages.error(request, 'Can\'t connect to MySQL database. %s' % str(e))
                    return render(request, self.template_name, {'step': self.step, 'form': form})


            open(env_file, 'a').write('\nDATABASE_URL=%s://%s:%s@%s:%s/%s' % (
                form.cleaned_data['engine'],
                form.cleaned_data['username'],
                form.cleaned_data['password'],
                form.cleaned_data['host'],
                form.cleaned_data['port'],
                form.cleaned_data['name']
            ))

        env = environ.Env(DEBUG=(bool, False), )
        env.read_env(env_file)
        settings.SETUP_COMPLETED = True
        settings.DATABASES['default'] = env.db('DATABASE_URL')

        return HttpResponseRedirect(reverse('setup:migration'))


class MigrateView(View):
    template_name = 'setup_migration.html'

    def get(self, request, *args, **kwargs):
        python_file = sys.executable
        manage_file = str(settings.ROOT_DIR.path('manage.py'))

        try:
            command = '%s migrate --noinput' % manage_file
            process = subprocess.Popen([python_file, ] + command.split(), stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE) # noqa
            (outStream, errStream) = process.communicate()
        except Exception as e:
            outStream = ''
            errStream = str(e)

        return render(request, self.template_name, {'step': 3, 'out': outStream, 'err': errStream})

    def post(self, request, *args, **kwargs):

        return HttpResponseRedirect(reverse('setup:user'))


class UserView(View):
    template_name = 'setup_user.html'
    form_class = UserForm

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'step': 4, 'form': self.form_class()})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if not form.is_valid():
            return render(request, self.template_name, {'step': 4, 'form': self.form_class()})

        user, _ = User.objects.get_or_create(
            email=form.cleaned_data['email'],
            username=form.cleaned_data['username'],
            defaults={'is_superuser': True, 'is_staff': True})
        user.set_password(form.cleaned_data['password'])
        user.save()

        return HttpResponseRedirect(reverse('setup:fixture'))


class FixtureView(View):
    template_name = 'setup_fixture.html'

    def get(self, request, *args, **kwargs):
        python_file = sys.executable
        manage_file = str(settings.ROOT_DIR.path('manage.py'))

        try:
            command = '%s loaddata' % manage_file
            process = subprocess.Popen([python_file, ] + command.split(), stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE) # noqa
            (outStream, errStream) = process.communicate()
        except Exception as e:
            outStream = ''
            errStream = str(e)

        return render(request, self.template_name, {'step': 5, 'out': outStream, 'err': errStream})


class CompleteView(TemplateView):

    def get_context_data(self, **kwargs):
        context = super(CompleteView, self).get_context_data(**kwargs)
        context['step'] = 6
        return context

app_setup/templates/migrate.html
{% extends 'setup_base.html' %}

{% block content %}
<h1>DATABASE CONFIGURED.</h1>
<h2>running migrations ... </h2>

{% if out %}
<div class="bs-callout bs-callout-info"> 
    <h4>Success</h4>
</div>
<div style="background-color: black; color: green; padding: 20px; margin-bottom: 20px;">
  {{ out | safe }}
</div>
{% endif %}

{% if err %}
<div class="bs-callout bs-callout-danger"> 
    <h4>Error</h4>
</div>
<div style="background-color: black; color: green; padding: 20px; margin-bottom: 20px;">
  {{ err | safe }}
</div>
{% endif %}

<form action="." method="post">
  {% csrf_token %}
  <button class="btn btn-primary" type="submit">Done</button>
</form>
{% endblock %}      

app_setup/templates/setup_base.html
<!doctype html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Proxy Setup</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.min.css" />
        <link rel="stylesheet" href="https://getbootstrap.com/docs/3.3/assets/css/docs.min.css" />

        <style type="text/css">
            footer {height: 40px; padding: 20px; font-size: 10px; color: gray;}
            .progress { margin-bottom: 0; border-radius: 0; height: 5px }
            .progress .progress-bar { background-image: none; background-color: orange }
            form legend { border-bottom: 0; color: #ccc; }  
            form .actions{ margin: 40px 0; }
            h1.page-header { margin-top: 0; }
            .nav-pills>li.active>a { background-color: orange; }
            .btn.btn-primary { background-image: none; background-color: #4d90fe; border: none; border-radius: 0; padding: 12px; }
        </style>

        {% block styles %} {% endblock %}
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <nav class="navbar navbar-inverse" style="border-radius: 0; background-image: none;">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <a class="navbar-brand" href="/setup"><img src="http://10.10.99.231:7000/static/img/invgate-logo.png" style="display: inline-block;"> Proxy Setup</a>
            </div>
          </div>  
        </nav>        

        <div class="container">
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 0;">
                <span class="sr-only">60% Complete</span>
              </div>
            </div>

            <div class="row wizard">
                <div class="col-xs-12">
                    <ul class="nav nav-pills nav-justified thumbnail">
                        <li class="disabled {% if step == 1 %}active{% endif %}"><a href="#">
                            <h4 class="list-group-item-heading">1. Welcome</h4>
                            <p class="list-group-item-text">Install Requirements</p>
                        </a></li>
                        <li class="disabled {% if step == 2 %}active{% endif %}"><a href="#">
                            <h4 class="list-group-item-heading">2. Environment</h4>
                            <p class="list-group-item-text">General Configurations</p>
                        </a></li>
                        <li class="disabled {% if step == 3 %}active{% endif %}"><a href="#">
                            <h4 class="list-group-item-heading">3. Database</h4>
                            <p class="list-group-item-text">Apply Migrations</p>
                        </a></li>
                        <li class="disabled {% if step == 4 %}active{% endif %}"><a href="#">
                            <h4 class="list-group-item-heading">4. Administration</h4>
                            <p class="list-group-item-text">Set User</p>
                        </a></li>
                        <li class="disabled {% if step == 5 %}active{% endif %}"><a href="#">
                            <h4 class="list-group-item-heading">5. Fixture</h4>
                            <p class="list-group-item-text">Load Initial Data</p>
                        </a></li>
                        <li class="disabled {% if step == 6 %}active{% endif %}"><a href="#">
                            <h4 class="list-group-item-heading">6. Completed</h4>
                            <p class="list-group-item-text">Done :)</p>
                        </a></li>
                    </ul>
                </div>
            </div>

            {% if messages %}
            <div class="bs-callout bs-callout-danger"> 
                <h4>Error:</h4> 
                {% for message in messages %}
                <p>{{message}}</p> 
                {% endfor %}
            </div>
            {% endif %}

            {% block content %}{% endblock %}                    
        </div>
        <footer>
            <p class="text-right"> &copy; Proxy Setup {% now 'Y'%}. </p>
        </footer>

        <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                var progress = (({{step}} * 100) / 6) + '%';
                $('.progress-bar').animate({width: progress}, 500);
            })
        </script>
        {% block scripts %}{% endblock %}
    </body>
</html>

app_setup/templates/setup_completed.html
{% extends 'setup_base.html' %}

{% block content %}

<h1 class="page-header">Completed !</h1>
<h2>Congrats. We finished configuring your proxy server.</h2>

<div>
    <a class="pull-right btn btn-primary" href="/">Great!.</a>
</div>
{% endblock %}

app_setup/templates/setup_environment.html
{% extends 'setup_base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h1 class="page-header">Configure your environment</h1>

{% crispy form %}

{% endblock %}


{% block scripts %}
<script type="text/javascript">
  
$(document).ready(function() {

  $('input[name=engine]').on('change', function(ev) {
    if ($(this).is(':checked')) {
      $('fieldset.db input').val('')

      if ($(this).val() === 'sqlite') {
        $('fieldset.db input').closest('.form-group').hide()
  
        $('input[name=name]').closest('.form-group').show();
        $('input[name=name]').val('db.sqlite3');
      }
      else {
        $('fieldset.db input').closest('.form-group').show()
      }

      if ($(this).val() === 'mysql') {
        $('input[name=host]').val('localhost')
        $('input[name=port]').val('3306')
      }
    }
  }) 

  $('input[name=engine]').trigger('change');

});

</script>

{% endblock %}                    

app_setup/templates/setup_fixture.html
{% extends 'setup_base.html' %}

{% block content %}
<h1 class="page-header">Init database data</h1>
<h2>Running fixtures ... (Move to AJAX in next version) </h2>

{% if out %}
<div class="bs-callout bs-callout-info"> 
    <h4>Success</h4>
</div>
<div style="background-color: black; color: green; padding: 20px; margin-bottom: 20px;">
  {{ out | safe }}
</div>
{% endif %}

{% if err %}
<div class="bs-callout bs-callout-danger"> 
    <h4>Error</h4>
</div>
<div style="background-color: black; color: green; padding: 20px; margin-bottom: 20px;">
  {{ err | safe }}
</div>
{% endif %}

<a href="{% url 'setup:completed' %}" class="btn btn-primary" >Finish wizard</a>
{% endblock %}      

app_setup/templates/setup_migration.html
{% extends 'setup_base.html' %}

{% block content %}
<h1 class="page-header">Configuring database</h1>
<h2>Running migrations ... (Move to AJAX in next version) </h2>

{% if out %}
<div class="bs-callout bs-callout-info"> 
    <h4>Success</h4>
</div>
<div style="background-color: black; color: green; padding: 20px; margin-bottom: 20px;">
  {{ out | safe }}
</div>
{% endif %}

{% if err %}
<div class="bs-callout bs-callout-danger"> 
    <h4>Error</h4>
</div>
<div style="background-color: black; color: green; padding: 20px; margin-bottom: 20px;">
  {{ err | safe }}
</div>
{% endif %}

<form action="." method="post">
  {% csrf_token %}
  <button class="btn btn-primary" type="submit">Configure admin user</button>
</form>
{% endblock %}      

app_setup/templates/setup_user.html
{% extends 'setup_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1 class="page-header">Configuring administrator access</h1>

{% crispy form %}

{% endblock %}

app_setup/templates/setup_welcome.html
{% extends 'setup_base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h1 class="page-header">Welcome !</h1>
<h2>This wizard will help you to configure your proxy server.</h2>

<p class="lead">Please check that you have the following requeriments installed:</p>
<ul class="lead">
    <li>MySql or Postgres or Orable databases</li>
    <li>Soft 2</li>
    <li>Soft 3</li>
</ul>
<p class="lead"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>

<div>
    <a class="pull-right btn btn-primary" href="{% url 'setup:environment' %}">Yes, I already installed all requirements.</a>
</div>

{% endblock %}